version: '3.8'

services:
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    # No complex volumes or configurations
    command: redis-server --appendonly no
    networks:
      - test-network

  redis-test:
    image: redis:6-alpine
    depends_on:
      - redis
    networks:
      - test-network
    command: sh -c "redis-cli -h redis ping && echo 'Redis is working!'"

networks:
  test-network:
    driver: bridge